version: '3.3'
services:
  web:
    build:
      context: .
    env_file: ./.env
    command: npm test
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:13.4-alpine
    container_name: werewolf-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=werewolf
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    logging:
      driver: none
